apiVersion: apps/v1
kind: Deployment
metadata:
  name: ship-cluster-worker-edit
spec:
  template:
    spec:
      nodeSelector:
        replicated/node-pool: privileged
      containers:
        - name: ship-cluster-worker
          image: 799720048698.dkr.ecr.us-east-1.amazonaws.com/ship-cluster-worker
          env:
            - name: INIT_NODE_SELECTOR
              value: untrusted
            - name: UPDATE_NODE_SELECTOR
              value: untrusted
            - name: EDIT_NODE_SELECTOR
              value: untrusted
            - name: USE_EC2_PARAMETERS
              value: "1"
            - name: AWS_REGION
              value: us-east-1
            - name: SHIP_IMAGE
              value: "replicated/ship"
            - name: SHIP_TAG
              value: "0.48.1"
            - name: SHIP_PULL_POLICY
              value: "IfNotPresent"
            - name: GITHUB_INTEGRATION_ID
              value: "16925"
