steps:
  - commands:
      - make -C worker build
    label: test-and-build
    plugins:
      - docker#v3.0.1:
          image: replicated/gitops-builder:buildkite
          always-pull: true
          workdir: /go/src/github.com/replicatedhq/ship-cluster
    artifact_paths:
      - "worker/bin/**/*"

  - wait

  - commands:
      - mkdir -p worker/bin worker/deploy/bin
      - buildkite-agent artifact download worker/bin/* . --step test-and-build
      - cp worker/bin/ship-cluster-worker worker/deploy/bin/ship-cluster-worker
      - chmod +x worker/deploy/bin/ship-cluster-worker
      - make -C worker build-enterprise
    branches: "master"
    retry:
      automatic: true

  - commands:
      - mkdir -p worker/bin worker/deploy/bin
      - buildkite-agent artifact download worker/bin/* . --step test-and-build
      - cp worker/bin/ship-cluster-worker worker/deploy/bin/ship-cluster-worker
      - chmod +x worker/deploy/bin/ship-cluster-worker
      - make -C worker build-staging
    branches: "master"
    retry:
      automatic: true
    env:
      AWS_PROFILE: replicated-staging
    plugins:
      - ecr#v2.0.0:
          login: true
          account_ids: "923411875752"

  - commands:
      - mkdir -p worker/bin worker/deploy/bin
      - buildkite-agent artifact download worker/bin/* . --step test-and-build
      - cp worker/bin/ship-cluster-worker worker/deploy/bin/ship-cluster-worker
      - chmod +x worker/deploy/bin/ship-cluster-worker
      - make -C worker build-production
    branches: "master"
    retry:
      automatic: true
    env:
      AWS_PROFILE: replicated-production
    plugins:
      - ecr#v2.0.0:
          login: true
          account_ids: "799720048698"

  - wait

  - commands:
      - make -C worker publish-enterprise
    branches: "master"
    retry:
      automatic: true

  - commands:
      - make -C worker publish-enterprise-aka
    branches: "master"
    retry:
      automatic: true

  - commands:
      - make -C worker publish-staging
    branches: "master"
    retry:
      automatic: true


  - block: "Release to production"
    branches: "master"

  - commands:
      - make -C worker publish-production
    branches: "master"
    retry:
      automatic: true
