apiVersion: v1
kind: Service
metadata:
  name: kotsadm-web
  labels:
    app: kotsadm-web
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30065
    port: 3000
    targetPort: http
  selector:
    app: kotsadm-web
