apiVersion: skaffold/v1beta11
kind: Config

profiles:
  - name: github
    deploy:
      kustomize:
        path: "./kustomize/overlays/github"

  - name: microk8s
    activation:
      - kubeContext: microk8s
    deploy:
      kustomize:
        path: "./kustomize/overlays/microk8s"
        flags:
          apply:
            - --validate=false  ## Skaffold turns CRDs into invalid yaml (https://github.com/GoogleContainerTools/skaffold/issues/1737)

build:
  local:
    useBuildkit: true

  artifacts:
    - image: ship-cluster-api
      context: "./api"
      docker:
        dockerfile: ./Dockerfile.skaffold

    - image: ship-cluster-ui
      context: "./web"
      sync:
        manual:
          - src: "src/**/*.jsx"
            dest: "./"
          - src: "src/**/*.js"
            dest: "./"
          - src: "src/**/*.png"
            dest: "./"
          - src: "src/**/*.scss"
            dest: "./"
          - src: "src/**/*.css"
            dest: "./"
      docker:
        dockerfile: ./Dockerfile.skaffold

    - image: ship-cluster-worker
      context: "./worker"
      docker:
        dockerfile: ./Dockerfile.skaffold

deploy:
  kustomize:
    path: "./kustomize/overlays/dev"
