apiVersion: schemas.schemahero.io/v1alpha2
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: app-config-cache
spec:
  database: kotsadm-postgres
  name: app_config_cache
  requires: []
  schema:
    postgres:
      primaryKey:
        - app_id
      columns:
      - name: app_id
        type: text
        constraints:
          notNull: true
      - name: config_path
        type: text
      - name: config_content
        type: text
      - name: config_values_path
        type: text
      - name: config_values_content
        type: text
      - name: updated_at
        type: timestamp without time zone
