apiVersion: schemas.schemahero.io/v1alpha2
kind: Table
metadata:
  name: app-downstream
spec:
  database: kotsadm-postgres
  name: app_downstream
  requires: []
  schema:
    postgres:
      primaryKey:
        - app_id
        - cluster_id
      columns:
      - name: app_id
        type: text
        constraints:
          notNull: true
      - name: cluster_id
        type: text
        constraints:
          notNull: true
      - name: downstream_name
        type: text
        constraints:
          notNull: true
      - name: current_sequence
        type: integer
