apiVersion: schemas.schemahero.io/v1alpha2
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: github-install
spec:
  database: ship-cluster-postgres
  name: github_install
  requires: []
  schema:
    postgres:
      primaryKey:
      - id
      columns:
      - name: id
        type: text
        constraints:
          notNull: true
      - name: installation_id
        type: integer
      - name: account_login
        type: text
      - name: account_type
        type: text
      - name: account_html_url
        type: text
      - name: sender_login
        type: text
      - name: organization_members_total
        type: integer
      - name: created_at
        type: timestamp without time zone
      - name: is_deleted
        type: boolean
        default: "false"
