apiVersion: schemas.schemahero.io/v1alpha2
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: kotsadm-params
spec:
  database: ship-cluster-postgres
  name: kotsadm_params
  requires: []
  schema:
    postgres:
      primaryKey:
      - key
      columns:
      - name: key
        type: text
      - name: password_bcrypt
        type: text
        constraints:
          notNull: true
