apiVersion: schemas.schemahero.io/v1alpha2
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: ship-update
spec:
  database: ship-cluster-postgres
  name: ship_update
  requires: []
  schema:
    postgres:
      primaryKey:
      - id
      columns:
      - name: id
        type: text
        constraints:
          notNull: true
      - name: watch_id
        type: text
        constraints:
          notNull: true
      - name: user_id
        type: text
      - name: result
        type: text
      - name: created_at
        type: timestamp without time zone
        constraints:
          notNull: true
      - name: started_at
        type: timestamp without time zone
      - name: finished_at
        type: timestamp without time zone


# alter table ship_update alter column user_id drop not null;
