apiVersion: schemas.schemahero.io/v1alpha2
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: ship-user
spec:
  database: ship-cluster-postgres
  name: ship_user
  requires: []
  schema:
    postgres:
      primaryKey:
      - id
      columns:
      - name: id
        type: text
        constraints:
          notNull: true
      - name: created_at
        type: timestamp without time zone
      - name: github_id
        type: integer
      - name: last_login
        type: timestamp without time zone
      
