steps:
  - label: "schema-fixtures"
    artifact_paths:
      - "migrations/fixtures/schema/fixtures.sql"
    plugins:
      - docker#v3.0.1:
          image: schemahero/schemahero:alpha
          always-pull: true
          workdir: /repo
          debug: true
          environment:
            - "uid=999"
          volumes:
            - "./migrations/fixtures:/out"
            - "./migrations/tables:/in"
          command: ["fixtures", "--input-dir", "/in", "--output-dir", "/out/schema", "--dbname", "ship-cloud", "--driver", "postgres"]

  - wait

  - commands:
      - buildkite-agent artifact download migrations/fixtures/schema/fixtures.sql . --step schema-fixtures
      - make -C migrations/fixtures deps build run
    label: "build-fixtures"
    plugins:
      - docker#v3.0.1:
          image: replicated/gitops-builder:buildkite
          always-pull: true
          workdir: /repo
    artifact_paths:
      - "migrations/fixtures/fixtures.sql"

  - wait

  - commands:
      - buildkite-agent artifact download migrations/fixtures/fixtures.sql . --step build-fixtures
      - make -C migrations/fixtures publish
    label: "publish-fixtures"
    branches: "master"

  - wait

  - trigger: "ship-cluster-web"
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"


  - trigger: "ship-cluster-worker"
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"

  - trigger: "ship-cluster-migrations"
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
