steps:
  - label: "schema-fixtures"
    artifact_paths:
      - "migrations/fixtures/schema/fixtures.sql"
    plugins:
      - docker#v3.0.1:
          image: schemahero/schemahero:alpha
          always-pull: true
          workdir: /repo
          debug: true
          user: 999
          environment:
            - "uid=999"
          volumes:
            - "./migrations/fixtures:/out"
            - "./migrations/tables:/in"
          command: ["fixtures", "--input-dir", "/in", "--output-dir", "/out/schema", "--dbname", "ship-cloud", "--driver", "postgres"]

  - wait

  - commands:
      - buildkite-agent artifact download migrations/fixtures/schema/fixtures.sql . --step schema-fixtures
      - make -C migrations/fixtures deps build run
    label: "build-fixtures"
    plugins:
      - docker#v3.0.1:
          image: replicated/gitops-builder:buildkite
          always-pull: true
          workdir: /repo
    artifact_paths:
      - "migrations/fixtures/fixtures.sql"

  - wait

  - commands:
      - buildkite-agent artifact download migrations/fixtures/fixtures.sql . --step build-fixtures
      - make -C migrations/fixtures publish
    label: "publish-fixtures"
    branches: "master"

  - wait

  - trigger: "kotsadm-migrations"
    async: false
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        GIT_TAG: "${BUILDKITE_TAG}"

  - trigger: "kotsadm-web"
    async: false
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        GIT_TAG: "${BUILDKITE_TAG}"

  - trigger: "kotsadm-operator"
    async: false
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        GIT_TAG: "${BUILDKITE_TAG}"

  - label: "publish-minio"
    commands:
      - make -C minio publish-latest
    branches: "master"
    agents:
      root-docker: "true"
      queue: root-docker

  - label: "release-minio"
    commands:
      - if [ ! -z "$BUILDKITE_TAG" ]; then make -C minio publish-release; fi
    agents:
      root-docker: "true"
      queue: root-docker
