apiVersion: apps/v1
kind: Deployment
metadata:
  name: ship-cluster-worker-edit
spec:
  template:
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: replicatedregistrykey
      containers:
        - name: ship-cluster-worker
          image: registry.replicated.com/ship-enterprise/ship-cluster-worker
          env:
            - name: SHIP_IMAGE
              value: "replicated/ship"
            - name: SHIP_TAG
              value: "0.49.0"
            - name: SHIP_PULL_POLICY
              value: "IfNotPresent"
            - name: LOG_LEVEL
              value: warn
            - name: S3_ENDPOINT
              value: >
                {{repl if ConfigOptionEquals "s3_type" "s3_type_embedded"}}http://minio.default.svc.cluster.local:9000/{{repl else}}{{repl ConfigOption "s3_endpoint"}}{{repl end}}
            - name: S3_BUCKET_NAME
              value: >
                {{repl if ConfigOptionEquals "s3_type" "s3_type_embedded"}}ship-enterprise{{repl else}}{{repl ConfigOption "s3_bucket"}}{{repl end}}
            - name: S3_ACCESS_KEY_ID
              value: >
                {{repl if ConfigOptionEquals "s3_type" "s3_type_embedded"}}{{repl ConfigOption "embedded_s3_access_key_id"}}{{repl else}}{{repl ConfigOption "s3_access_key_id"}}{{repl end}}
            - name: S3_SECRET_ACCESS_KEY
              value: >
                {{repl if ConfigOptionEquals "s3_type" "s3_type_embedded"}}{{repl ConfigOption "embedded_s3_secret_access_key"}}{{repl else}}{{repl ConfigOption "s3_secret_access_key"}}{{repl end}}
            - name: S3_BUCKET_ENDPOINT
              value: >
                {{repl if ConfigOptionEquals "s3_type" "s3_type_embedded"}}true{{repl else}}{{repl end}}
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: ship-enterprise-postgres
                  key: uri
            - name: GITHUB_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: github-app-private-key
                  key: private-key.pem
            - name: GITHUB_INTEGRATION_ID
              value: '{{repl ConfigOption "github-integrationid"}}'
