apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: controller-manager
  namespace: ship-cd-system
spec:
  template:
    spec:
      imagePullSecrets:
        - name: replicatedregistrykey
      containers:
      - image: registry.replicated.com/ship-enterprise/ship-cd
        name: manager
