apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kotsadm-api-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - kotsadm-application-metadata
  verbs:
  - get
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - registry-creds
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - delete
  - list
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kotsadm-api-rolebinding
subjects:
- kind: ServiceAccount
  name: kotsadm-api
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kotsadm-api-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kotsadm-api
