apiVersion: apps/v1
kind: Deployment
metadata:
  name: ship-cluster-api
spec:
  template:
    spec:
      containers:
        - name: ship-cluster-api
          env:
            - name: SESSION_KEY
              valueFrom:
                secretKeyRef:
                  name: session
                  key: key
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: ship-postgres   # This secret is created in the ship-cluster-db project
                  key: uri
            - name: INIT_SERVER_URI
              value: "http://init-server:3000"
            - name: WATCH_SERVER_URI
              value: "http://watch-server:3000"
            - name: PINO_LOG_PRETTY
              value: "1"
            - name: S3_BUCKET_NAME
              value: "shipbucket"
            - name: S3_ENDPOINT
              value: http://ship-cluster-s3.default.svc.cluster.local:4569/
            - name: S3_ACCESS_KEY_ID
              value: not-a-key
            - name: S3_SECRET_ACCESS_KEY
              value: not-a-secret
            - name: S3_BUCKET_ENDPOINT
              value: "true"
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: github-app
                  key: client-id
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: github-app
                  key: client-secret
            - name: GITHUB_INTEGRATION_ID
              valueFrom:
                secretKeyRef:
                  name: github-app
                  key: integration-id
            - name: SHIP_API_ENDPOINT
              value: http://ship-cluster-api.default.svc.cluster.local:3000
            - name: SHIP_API_ADVERTISE_ENDPOINT
              value: http://docker.for.mac.localhost:30065
            - name: GRAPHQL_PREM_ENDPOINT
              value: http://graphql-api-prem:3000/graphql
          volumeMounts:
            - name: github-app-private-key
              mountPath: /keys/github
              readOnly: true
