apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotsadm-api
spec:
  selector:
    matchLabels:
      app: kotsadm-api
  template:
    metadata:
      labels:
        app: kotsadm-api
    spec:
      restartPolicy: Always
      containers:
        - name: kotsadm-api
          image: kotsadm-api
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 200m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 500Mi
          ports:
            - name: http
              containerPort: 3000
            - name: debug
              containerPort: 9229
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
