bases:
  - ../../base
  - ../../../web/kustomize/overlays/dev
  - ../../../api/kustomize/overlays/dev
  - ../../../operator/kustomize/overlays/dev
  - ../../../migrations/kustomize/overlays/dev
  - ./minio
